// <auto-generated />
namespace WorldsProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class _03182015update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_03182015update));
        
        string IMigrationMetadata.Id
        {
            get { return "201503190237582_03182015update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
